#!/bin/bash -e

export DEBUG_OR_RELEASE=$1
export ARCH=$2

if test -z "$ARCH" -o -z "$DEBUG_OR_RELEASE"
then
    echo "Usage: <mode> <arch>"
    echo "  mode is one of: debug, release"
    echo "  arch is one of: i386, arm, amd64"
    exit 1
fi

pushd baseq2
md5sum -c reference.txt || {
    if test -e pak0.pak
    then
        echo "baseq2/pak0.pak does not match the expected MD5 sum"
    else
        echo "baseq2/pak0.pak is not present"
    fi
    echo "Please copy pak0.pak from a Quake 2 installation"
    exit 1
}

pushd ../linux/$DEBUG_OR_RELEASE$ARCH/
export BUILD=$PWD
popd
popd
ln -sf $BUILD/quake2 .

pushd q2dq2
rm -f config.cfg   
rm -rf save
popd


