#!/bin/bash -xe

export DEBUG_OR_RELEASE=debug
export ARCH=amd64
export ENDFRAME=10000
export REFDATA=$PWD/frames.debug.i386.dat

./setup_links $DEBUG_OR_RELEASE $ARCH
gdb --args ./quake2  +game q2dq2 +set vid_ref headless

