#!/bin/bash -xe

export DEBUG_OR_RELEASE=$1
export ARCH=$2
export ENDFRAME=10000

./setup_links $DEBUG_OR_RELEASE $ARCH
./quake2  +game q2dq2 +set vid_ref headless  || true


mv frames.dat frames.$DEBUG_OR_RELEASE.$ARCH.dat || true
mv crc.dat crc.$DEBUG_OR_RELEASE.$ARCH.dat



