#!/bin/bash -xe

export ARCH=i386

./setup_links debug $ARCH
./quake2  +game q2dq2 +set vid_ref headless  || true
mv crc.dat crc.debug.dat

./setup_links release $ARCH
./quake2  +game q2dq2 +set vid_ref headless  || true
mv crc.dat crc.release.dat



