#!/bin/bash -e

export DEBUG_OR_RELEASE=$1
export ARCH=$2

if test -z "$ARCH" -o -z "$DEBUG_OR_RELEASE"
then
    echo "Usage: <mode> <arch>"
    echo "  mode is one of: debug, release"
    echo "  arch is one of: i386, arm, amd64"
    exit 1
fi

pushd baseq2
pushd ../linux/$DEBUG_OR_RELEASE$ARCH/
export BUILD=$PWD
popd
ln -sf $BUILD/game$ARCH.so
popd
ln -sf $BUILD/ref_headless.so
ln -sf $BUILD/ref_softx.so
ln -sf $BUILD/quake2 .
pwd > quake2.conf

pushd q2dq2
rm -f config.cfg   
rm -rf save
popd


