#!/bin/bash -xe

cd /home/jack/durden/Quake-2/linux

cd debugi386


cd baseq2
ln -sf ../gamei386.so gamei386.so

cd ..
export DISPLAY=:0 
rm -f q2dq2/config.cfg   
rm -rf q2dq2/save

./quake2  +game q2dq2 +set vid_ref headless
cd ..


cd releasei386
ln -sf ../debugi386/baseq2
ln -sf ../debugi386/q2dq2
ln -sf ../debugi386/quake2.conf

cd baseq2
ln -sf ../gamei386.so gamei386.so

cd ..
export DISPLAY=:0 
rm -f q2dq2/config.cfg   
rm -rf q2dq2/save

./quake2  +game q2dq2 +set vid_ref headless

